Developer checklist of Jupiter
racker/jupiter pull request #122
Opened 2020-11-25 17:11 UTC by nicko-winner

Hey all, since we don't have web-o-mates automated just yet with Jupiter, I would like to document a more manual process in our PR's we can follow in the mean time. I'm looking for any feedback or thoughts on what will my our processes better, and if an item in the template that seems like it would detract from our workflow, please say so as well. Thanks!

2020-11-25 18:11 UTC, usethecodeluke requested changes

2020-11-25 18:11 UTC, usethecodeluke commented on .github/pull_request_template.md
> +### PR Checklist before asking for +2 from Peers.
- [ ] Have you deployed to staging?

2020-11-25 18:11 UTC, usethecodeluke commented on .github/pull_request_template.md
> +### PR Checklist before asking for +2 from Peers.
- [ ] Have you validated the new / modified functionality in staging?

2020-11-25 18:28 UTC, usethecodeluke requested changes

2020-11-25 18:28 UTC, usethecodeluke commented on .github/pull_request_template.md
> +- [ ] No console errors where detected during validation?
```suggestion
- [ ] Were any console errors detected during validation?
```

2020-11-25 18:28 UTC, usethecodeluke commented on .github/pull_request_template.md
> +- [ ] Did you include a screenshots before and after demoing any changed UI functionality?
```suggestion
- [ ] Did you include screenshots from before and after which demo any changed UI functionality?
```

2020-11-25 18:42 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] No console errors where detected during validation?
Hmm, so far all the checkbox if the other items are checked is mostly a good thing, one did their diligence, and they indicate one can proceed. In this case if the checkbox is checked if a negative thing. 

What about this? I will move it up higher in the list so it is done before one gets to staging. Main reason for this one is to discourage merging of code with console errors in it, as they can add up if folks are not looking out for them.

- [x]  Did you check for console errors in browser?

2020-11-26 13:21 UTC, anuritjain commented on .github/pull_request_template.md
> +- [ ] Does this PR require more complete testing, such as an full regression before it is deployed?
should we add one more point in order to be extra cautious while merging into master, as it will deploy directly to prod?

2020-11-30 19:20 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Does this PR require more complete testing, such as an full regression before it is deployed?
sure, what do you think of this?
```suggestion
- [ ] Does this PR require more complete testing, such as a full regression before it is deployed?
- [ ] I feel highly confident this code will deploy to production without issues or bugs upon merging into master. (If you still have concerns or open issues, please note them here. If risk factors can not be mitigated a change request may need to be opened for this PR before it merges.)
```

2020-12-01 05:01 UTC, anuritjain commented on .github/pull_request_template.md
> +- [ ] Does this PR require more complete testing, such as an full regression before it is deployed?
yeah looks perfect!

2020-12-01 06:40 UTC, anuritjain approved these changes

2020-12-01 16:38 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Did you run the automated [Web-o-mates overnight tests](https://cq-portal.webomates.com/#/dashboard?product=95) on staging by clicking on the center circle in the CQ portal?
```suggestion
- [ ] Where you able to signup successfully?
- [ ] Did you run the automated [Web-o-mates overnight tests](https://cq-portal.webomates.com/#/dashboard?product=95) on staging by clicking on the center circle in the CQ portal?
```

2020-12-01 16:41 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] No console errors where detected during validation?
```suggestion
- [ ]  Where you able to signup successfully with no console errors?
```

2020-12-01 16:43 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Did you check for console errors in browser?
```suggestion
- [ ] Did you check for console errors in browser? 
```
```suggestion
```

2020-12-01 16:44 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Did you check for console errors in browser?
```suggestion
- [ ] Did you add component tests for any new code?
```

2020-12-01 16:46 UTC, vaibhavdubey08 approved these changes

2020-12-01 16:54 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Have you validated the new / modified functionality in staging?
```suggestion
- [ ] Have you validated the new / modified functionality in staging?
```

2020-12-01 16:59 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Where you able to signup successfully with no console errors?
```suggestion
- [ ] Where you able to signup successfully with no console errors?
- [ ] Have you deployed to and validated your changes in staging?
```

2020-12-01 17:39 UTC, nicko-winner commented on .github/pull_request_template.md
> +- [ ] Have you deployed to and validated your changes in staging?
```suggestion
- [ ] Have you deployed and validated your changes in staging?
```

2020-12-09 18:22 UTC, usethecodeluke approved these changes

2020-12-09 18:35 UTC, abrande approved these changes

2020-12-22 16:38 UTC, merged