Jupiter-30: set signup descrition for webomates test accounts
racker/jupiter pull request #134
Opened 2020-12-23 15:15 UTC by anuritjain

# Description
Signup Description for Webomates Automated Tests account

### What are the relevant story cards/tickets? Any additional PRs or other references?
Jira: https://jira.rax.io/browse/JUPITER-30

### PR Checklist before asking for +2 from peers.
- [ ] Did you include screenshots for changed UI functionality?
- [ ] Did you add component tests for any new code?
- [ ] Where you able to signup successfully with no console errors?
- [ ] Have you deployed and validated your changes in staging?
- [ ] Did you run the automated [Web-o-mates overnight tests](https://cq-portal.webomates.com/#/dashboard?product=95) on staging by clicking on the center circle in the CQ portal?
- [ ] Did you attach screen shots of results in this PR?
- [ ] Does this PR require more complete testing, such as a full regression before it is deployed?
- [ ] Have you documented any known deployment risks in this PR (If risk factors can not be mitigated a change request may need to be opened for this PR before it merges.)
### Before merging to master
- [ ] I notified #jupiter-dev I am going to do a deployment before merging to master.

2020-12-23 15:34 UTC, abrande requested changes

2020-12-23 15:34 UTC, abrande commented on utils/signup.js
> +    description: values.userInfo.accountName === 'webomates' ? 'CLOUD_TEST_SIGNUP_JUPITER'
I think it could be useful to have a couple test cases for this condition

2020-12-23 15:54 UTC, anuritjain commented on utils/signup.js
> +    description: values.userInfo.accountName === 'webomates' ? 'CLOUD_TEST_SIGNUP_JUPITER'
added tests for this condition.

2020-12-23 17:13 UTC, abrande approved these changes

2020-12-24 13:23 UTC, vaibhavdubey08 approved these changes

2020-12-24 14:17 UTC, nicko-winner reviewed
Code looks looks. Please wait until we are out of moratorium to deploy it.

2021-01-11 14:46 UTC, nicko-winner commented
Looks like smartling is not returning with a status even though they seem to have gotten the job a translators canceled it because there are no translations being added. This seems to be normal practice from what I see with other smartling jobs. It seems safe to deploy this PR anyway via Administrator privileges, but in the future it would be nice to find a way in smartling to get that status to report back correctly for jobs that don't have new translations.

2021-01-11 14:48 UTC, merged