JUPITER-48, 47: enabled CAD for Rackspace & Onica account types
racker/jupiter pull request #138
Opened 2021-01-21 13:37 UTC by anuritjain

# Description
CAD currency for updation for Rackspace & Onica Customers
https://jira.rax.io/browse/JUPITER-48
https://jira.rax.io/browse/JUPITER-47

### PR Checklist before asking for +2 from peers.
- [ ] Did you include screenshots for changed UI functionality?
- [ ] Did you add component tests for any new code?
- [ ] Were you able to signup successfully with no console errors?
- [ ] Have you deployed and validated your changes in staging?
- [ ] Did you run the automated [Web-o-mates overnight tests](https://cq-portal.webomates.com/#/dashboard?product=95) on staging by clicking on the center circle in the CQ portal?
- [ ] Did you attach screenshots of results in this PR?

### Before merging to master
- [ ] I notified #jupiter-dev I am going to do a deployment before merging to master.

2021-01-21 17:27 UTC, abrande approved these changes

2021-01-21 17:27 UTC, abrande commented on app/components/SignUp/BillingInfo/CurrencySelector.js
> +      disabled: customerType === 'rbu'
Is CAD available now if they don't live in Canada?

2021-01-21 17:27 UTC, abrande commented on i18n/en-US/account.json
> +    "translation" : "For Rackspace & Onica customers, you can select CAD."
It looks like based on this ticket AWS, Azure, and GCP, Onica customers may select CAD. You can follow up with Chris Moyer if you'd like guidance on the wording. https://jira.rax.io/browse/INTAKE-841

2021-01-22 14:21 UTC, anuritjain commented on i18n/en-US/account.json
> +    "translation" : "For Rackspace & Onica customers, you can select CAD."
sure

2021-01-28 15:50 UTC, nicko-winner commented on i18n/en-US/account.json
> +    "translation" : "For Rackspace & Onica customers, you can select CAD."
In last standup parking lot it was determined best to simply remove the tooltip. See comments in: https://jira.rax.io/browse/JUPITER-47

2021-01-28 16:19 UTC, anuritjain commented on i18n/en-US/account.json
> +    "translation" : "For Rackspace & Onica customers, you can select CAD."
removed keys from i18n repo.

2021-01-28 16:35 UTC, abrande requested changes

2021-01-29 05:33 UTC, anuritjain commented on app/components/SignUp/BillingInfo/CurrencySelector.js
> +      disabled: !cadAvailable
fixed

2021-01-29 05:39 UTC, anuritjain commented on app/components/SignUp/BillingInfo/CurrencySelector.test.js
> +        });
modified tests as mentioned.

2021-01-29 15:03 UTC, abrande approved these changes

2021-01-29 15:05 UTC, nicko-winner approved these changes

2021-01-29 15:27 UTC, merged